const mockState = {
  user: "Brian",
  notifications: 0,
  plans: [
    {
      name: "Single-Stroke Mastery 1",
      author: "Brian D. Sauls",
      modified: "12.03.2024",
      published: false,
      folder: "Technique",
    },
    {
      name: "Single-Stroke Mastery 2",
      author: "Brian D. Sauls",
      modified: "12.03.2024",
      published: false,
      folder: "Technique",
    },
    {
      name: "Double-Stroke Mastery",
      author: "Brian D. Sauls",
      modified: "10.03.2024",
      published: false,
      folder: "Technique",
    },
    {
      name: "Bassdrum Independence",
      author: "Brian D. Sauls",
      modified: "10.03.2024",
      published: false,
      folder: "Independence",
    },
    {
      name: "Jazz Independence",
      author: "Brian D. Sauls",
      modified: "10.03.2024",
      published: false,
      folder: "Jazz",
    },
    {
      name: "Chopz",
      author: "Brian D. Sauls",
      modified: "10.03.2024",
      published: false,
      folder: "Chops",
    },
  ],
  exercises: [
    {
      name: "Singles Pyramid",
      author: "Jojo Mayer",
      modified: "23.08.2024",
      published: true,
      folder: "Technique",
    },
    {
      name: "Doubles Pyramid",
      author: "Jojo Mayer",
      modified: "23.08.2024",
      published: true,
      folder: "Technique",
    },
    {
      name: "BD Indepence 1",
      author: "Brian D. Sauls",
      modified: "23.08.2024",
      published: false,
      folder: "Independence",
    },
    {
      name: "BD Indepence 2",
      author: "Brian D. Sauls",
      modified: "23.08.2024",
      published: false,
      folder: "Independence",
    },
    {
      name: "Jazz Comping",
      author: "Brian D. Sauls",
      modified: "23.08.2024",
      published: false,
      folder: "Jazz",
    },
    {
      name: "Singles Application",
      author: "Brian D. Sauls",
      modified: "23.08.2024",
      published: false,
      folder: "Independence",
    },
    {
      name: "Doubles Application",
      author: "Brian D. Sauls",
      modified: "23.08.2024",
      published: false,
      folder: "Independence",
    },
    {
      name: "Basic Chop 1",
      author: "Brian D. Sauls",
      modified: "23.08.2024",
      published: false,
      folder: "Chops",
    },
    {
      name: "Basic Chop 2",
      author: "Brian D. Sauls",
      modified: "23.08.2024",
      published: false,
      folder: "Chops",
    },
    {
      name: "Basic Chop 3",
      author: "Brian D. Sauls",
      modified: "23.08.2024",
      published: false,
      folder: "Chops",
    },
  ],
  folders: {
    plans: ["Technique", "Jojo Mayer", "Favorites", "Jazz", "Independence", "Chopz"],
    exercises: ["Technique", "Jazz", "Independence", "Chopz"],
  },
};

export default mockState;
